import { notFound } from 'next/navigation';
import { fetchPlainHtml, EDS_ORIGIN } from '../../../lib/eds/fetch.js';
import { parseEds } from '../../../lib/eds/parse.js';
import { renderNode } from '../../../lib/eds/render.js';

// Pre-render every published page at build time from the EDS query-index feed (SSG). Pages
// not in the feed (or added later) still resolve on demand via ISR, since dynamicParams
// defaults to true. The feed is defined by helix-query.yaml and generated by EDS on publish;
// until it exists this returns [] and all routes stay dynamic — the build never breaks.
export async function generateStaticParams() {
  try {
    const res = await fetch(`${EDS_ORIGIN}/query-index.json`, { next: { revalidate: 3600 } });
    if (!res.ok) return [];
    const { data = [] } = await res.json();
    return data
      .map(({ path }) => path)
      .filter((p) => typeof p === 'string')
      // '/' → { slug: [] } (the index route); '/foo/bar.html' → { slug: ['foo', 'bar'] }
      .map((p) => ({ slug: p.replace(/\.html$/, '').split('/').filter(Boolean) }));
  } catch {
    return [];
  }
}

// Catch-all route: any path → fetch EDS .plain.html → parse → render via block registry.
// A React Server Component, so static content ships zero client-side JavaScript.
export default async function Page({ params }) {
  const { slug } = await params;
  const path = (slug ?? []).join('/');

  const html = await fetchPlainHtml(path);
  if (html === null) notFound(); // missing page / non-page request → 404, not 500

  const tree = parseEds(html);

  return <main>{tree.map((node, i) => renderNode(node, i))}</main>;
}
